### Creating arrays from scratch

In [ ]:
import numpy as np

In [ ]:
import numpy as np
zeros = np.zeros((3, 4))
print("zeros array:\n", zeros)


ones = np.ones((3, 3))
print("ones array:\n", ones)

full = np.full((2, 2), 7)
print("full array:\n", full)


random = np.random.random((2, 2))
print("random array:\n", random)


sequence = np.arange(0, 10, 2)  # [start, stop, step] means 0 to 10 with step of 2

print("sequence array:\n", sequence)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
full array:
 [[7 7]
 [7 7]]
random array:
 [[0.83271297 0.73897494]
 [0.75337889 0.48908547]]
sequence array:
 [0 2 4 6 8]
