### Sorting

In [ ]:
import numpy as np
unsorted = np.array([2,4,5,4,6,8,7])
print("Sorted Array:", np.sort(unsorted))

arr_2d_unsorted = np.array([[2, 4, 5], [4, 6, 8], [7, 1, 3]])
print("Sorted 2D Array by column:\n", np.sort(arr_2d_unsorted, axis=0))

Sorted Array: [2 4 4 5 6 7 8]
Sorted 2D Array:
 [[2 1 3]
 [4 4 5]
 [7 6 8]]


### Filter

In [3]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers: ", even_numbers)

Even Numbers:  [ 2  4  6  8 10]


### Filter with mask

In [ ]:
mask = numbers > 5  # Mask is an expression that returns a boolean array
print("Numbers greater than 5: ", numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


### Combined numpy Arrays

In [5]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
arr3 = np.concatenate((arr1, arr2))
print("Concatenated Array:", arr3)

Concatenated Array: [ 1  2  3  4  5  6  7  8  9 10]


### Compatible Array

In [ ]:
## Array Compatibility is about to check if two arrays are same in shape or not

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Array Compatibility Check:", a.shape == b.shape)  

Array Compatibility Check: True


In [ ]:
original = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((original, new_row))  # vstack adds a new row(means vertical stack)
print(original)
print("Array after adding new row:\n", with_new_row)

# Adding a new column to the original array
new_column = np.array([[7], [8]])
with_new_column = np.hstack((original, new_column)) # hstack adds a new column (means horizontal stack)
print("Array after adding new column:\n", with_new_column)




[[1 2]
 [3 4]]
Array after adding new row:
 [[1 2]
 [3 4]
 [5 6]]
Array after adding new column:
 [[1 2 7]
 [3 4 8]]


### Deletion

In [8]:
arr = np.array([1,2,3,4,5])
deletion = np.delete(arr, 2)  # Deletes the second element (index 2)
print("Original Array:\n", arr)
print("Array after Deletion: ", deletion)

Original Array:
 [1 2 3 4 5]
Array after Deletion:  [1 2 4 5]
