In [2]:
## Create numpy array of even numbers from 2 to 20

import numpy as np
even_arr = np.arange(2,21,2)
print(even_arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [3]:
## Reshape a 1D array to 2D array
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [4]:
### Element wise operations
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

## Element-wise addition
c = a + b
print("Element-wise addition:", c)
## Element-wise multiplication
d = a * b
print("Element-wise multiplication:", d)
## Element-wise division
e = a / b
print("Element-wise division:", e)

Element-wise addition: [11 22 33]
Element-wise multiplication: [10 40 90]
Element-wise division: [10. 10. 10.]


In [5]:
## Find max and its index
arr = np.array([4, 9, 2, 10, 7])
max_value = np.max(arr)
max_index = np.argmax(arr)
print("Max value:", max_value)
print("Index of max value:", max_index)

Max value: 10
Index of max value: 3


In [6]:
## Boolean extracting. Extract elements greater than 10

arr = np.array([5, 10, 15, 20, 25])
extracted = arr[arr > 10]
print("Elements greater than 10:", extracted)

Elements greater than 10: [15 20 25]


In [7]:
## Normalize numpy array
arr = np.array([10, 20, 30, 40, 50])
normalized_arr = (arr-arr.min()) / (arr.max() - arr.min())
print("Normalized array:", normalized_arr)

Normalized array: [0.   0.25 0.5  0.75 1.  ]


In [10]:
## Replace all odd numbers with -1
arr = np.array([1, 2, 3, 4, 5, 6])
replaced_arr = arr.copy()
replaced_arr[replaced_arr % 2 == 1] = -1
print("Array with odd numbers replaced by -1:", replaced_arr)

Array with odd numbers replaced by -1: [-1  2 -1  4 -1  6]


In [11]:
## Get common elements between two arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])

common_elements = np.intersect1d(a, b)
print("Common elements between a and b:", common_elements)

Common elements between a and b: [4 5]


In [12]:
### Create a 5x5 Matrix with Row Values from 0 to 4
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [15]:
## Extract Rows with a Condition not use loop
arr = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])

condition = arr[:, 0] > 10  # Condition on the first column
extracted_rows = arr[condition]
print("Rows where first column > 10:\n", extracted_rows)


Rows where first column > 10:
 [[20 25 30]
 [35 40 45]]
